// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_bhjeOxLRuf55qKmsop07cEgQVj42Qls',
    appId: '1:961303264927:web:421eb45d49915dbfe62caa',
    messagingSenderId: '961303264927',
    projectId: 'spots-expenses',
    authDomain: 'spots-expenses.firebaseapp.com',
    storageBucket: 'spots-expenses.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpWHEjLYbmH_ImbQk0gLzwPot1ShXnPs',
    appId: '1:961303264927:android:1db5c271fe48c7b7e62caa',
    messagingSenderId: '961303264927',
    projectId: 'spots-expenses',
    storageBucket: 'spots-expenses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkcD9YWozQPtLx1Fdi-bDXVXfogXn-wOo',
    appId: '1:961303264927:ios:4e57c8cfd2a08b09e62caa',
    messagingSenderId: '961303264927',
    projectId: 'spots-expenses',
    storageBucket: 'spots-expenses.appspot.com',
    iosClientId:
        '961303264927-9dqlohiksdgp9ipebu7ftes60sag3tf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotsExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkcD9YWozQPtLx1Fdi-bDXVXfogXn-wOo',
    appId: '1:961303264927:ios:4e57c8cfd2a08b09e62caa',
    messagingSenderId: '961303264927',
    projectId: 'spots-expenses',
    storageBucket: 'spots-expenses.appspot.com',
    iosClientId:
        '961303264927-9dqlohiksdgp9ipebu7ftes60sag3tf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotsExpenses',
  );
}
